### ISSUE TITLE
Grover::Error: SyntaxError: Invalid regular expression: /\[\s*(?<attribute>\w+)\s*=\s*(?<quote>"|')(?<value>\\.|.*?(?=\k<quote>))\k<quote>\s*\]/: Invalid group

### ISSUE THREAD

**Issue by GenaroLegaspiJr** [Studiosity/grover#144]
I did this 

gr = Grover.new("page_url")
pdf = gr.to_pdf

then got this error

```
Grover::Error: SyntaxError: Invalid regular expression: /\[\s*(?<attribute>\w+)\s*=\s*(?<quote>"|')(?<value>\\.|.*?(?=\k<quote>))\k<quote>\s*\]/: Invalid group
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/grover-0.12.3/lib/grover/processor.rb:53:in `parse_package_error'
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/grover-0.12.3/lib/grover/processor.rb:48:in `ensure_packages_are_initiated'
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/grover-0.12.3/lib/grover/processor.rb:19:in `convert'
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/grover-0.12.3/lib/grover.rb:50:in `to_pdf'
	from (irb):2
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/commands/console.rb:110:in `start'
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/commands/console.rb:9:in `start'
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/administrator/score_finder/shared/bundle/ruby/2.3.0/gems/railties-4.2.7/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:15:in `require'
	from bin/rails:15:in `<main>'
```

What did I do wrong? What am I missing?

**Comment by abrom** [comment]
If I were to guess I'd say you were using a really really old version of NodeJS. One that is incompatible with the version of Puppeteer you have installed. 

From the Puppeteer docs:
```
Note: Prior to v1.18.1, Puppeteer required at least Node v6.4.0. Versions from v1.18.1 to v2.1.0 rely on Node 8.9.0+. Starting from v3.0.0 Puppeteer starts to rely on Node 10.18.1+. All examples below use async/await which is only supported in Node v7.6.0 or greater.
```

**Comment by GenaroLegaspiJr** [comment]
> If I were to guess I'd say you were using a really really old version of NodeJS. One that is incompatible with the version of Puppeteer you have installed.
> 
> From the Puppeteer docs:
> 
> ```
> Note: Prior to v1.18.1, Puppeteer required at least Node v6.4.0. Versions from v1.18.1 to v2.1.0 rely
> on Node 8.9.0+. Starting from v3.0.0 Puppeteer starts to rely on Node 10.18.1+. All examples below
> use async/await which is only supported in Node v7.6.0 or greater.
> ```

here's my node version

```
administrator@ip-172-31-47-113:~$ nodejs -v
v8.10.0
```

**Comment by abrom** [comment]
That is a really really old version of node. v8 and v10 are already EOL and v12 is quite a way into its maintenance life...

And what about the Puppeteer version? Given the compatibility notes I posted, you'd need to be using < v3.0 That's a really old version too!
