### ISSUE TITLE
Precompile Error

### ISSUE THREAD

**Issue by Mohamed-Zkaria** [Studiosity/grover#245]
I was trying to build for staging but the precompilation fails with an uglifier error, 
I tried terser but it fails with a different error, the error with terser is referring to css classes that don't exist in the entire project. any suggestions to how to debug this please? 
error log: 
```
 rails aborted!
646.2 Sass::SyntaxError: Invalid CSS after "...select-bg-img: ": expected "}", was "url("data:image..."
646.2 (sass):2449
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:1308:in `expected'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:1238:in `expected'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:1233:in `tok!'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:690:in `block'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:681:in `ruleset'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:707:in `block_child'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:700:in `block_contents'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:137:in `stylesheet'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/scss/parser.rb:41:in `parse'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/engine.rb:414:in `_to_tree'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sass-3.7.4/lib/sass/engine.rb:290:in `render'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:48:in `call'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:28:in `call'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:67:in `block (3 levels) in define'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
646.2 /usr/local/bundle/ruby/2.7.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/task.rb:66:in `block (2 levels) in define'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
646.2 /usr/local/bundle/ruby/2.7.0/gems/ddtrace-1.20.0/lib/datadog/tracing/contrib/rake/instrumentation.rb:30:in `execute'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
646.2 /usr/local/bundle/ruby/2.7.0/bundler/gems/rails-b2d75a50fd6e/railties/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
646.2 /usr/local/bundle/ruby/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
646.2 /usr/local/bundle/ruby/2.7.0/bundler/gems/rails-b2d75a50fd6e/railties/lib/rails/commands/rake/rake_command.rb:20:in `perform'
646.2 /usr/local/bundle/ruby/2.7.0/bundler/gems/rails-b2d75a50fd6e/railties/lib/rails/command.rb:48:in `invoke'
646.2 /usr/local/bundle/ruby/2.7.0/bundler/gems/rails-b2d75a50fd6e/railties/lib/rails/commands.rb:18:in `<top (required)>'
646.2 bin/rails:4:in `require'
646.2 bin/rails:4:in `<main>'
646.2 Tasks: TOP => assets:precompile
------
failed to solve: process "/bin/sh -c SECRET_KEY_BASE_DUMMY=\"1\" SECRET_KEY_BASE=\"1\"  RAILS_ENV=staging bundle exec rails assets:precompile --trace" did not complete successfully: exit code: 1
```

**Comment by abrom** [comment]
This has absolutely nothing to do with the grover project. It doesn't have any CSS let alone SCSS. I'd suggest you go looking for what ever has included the SCSS it is complaining about. ie something like: `select-bg-img: url("data:image`

**Comment by Mohamed-Zkaria** [comment]
> This has absolutely nothing to do with the grover project. It doesn't have any CSS let alone SCSS. I'd suggest you go looking for what ever has included the SCSS it is complaining about. ie something like: `select-bg-img: url("data:image`

I didn't get this error until I used grover.
